version: '3'
services:
  mysql:
    image: mysql 
    #restart: always
    
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root 
    ports:
      - 3306:3306
    
      
  api:
    #links: 
    #  -mysql
    build:
     context: ./mysql
     dockerfile: Dockerfile
    
    volumes:
     - ./src:/TechDoJo
    
    #restart: always
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=Root
  
