version: '3'
services:
  mysql:
    image: mysql 

    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root 
      
   api:
    build:
     context: ./
     dockerfile: Dokerfile
  
