version: '3'
services:
  mysql:
    image: mysql 
    #restart: always
    
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root 
      
  api:
    build:
     context: ./mysql
     dockerfile: Dockerfile
    
    volumes:
     - ./src:/go/src
    
    #restart: always
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=Root
  
